import { useEffect, useState } from "react";
import { Button, Select, Textarea } from "flowbite-react";
import { HelpTooltip } from "../../../components/common/HelpTooltip";
import { ToolToast } from "../../../components/common/ToolToast";
import { ToolPageLayout } from "../../../components/layout/ToolPageLayout";
import { usePageTitle } from "../../../hooks/usePageTitle";
import type { ToolExample } from "../../../types/toolPage";
import type { ToastMessage, ToastTone } from "../../../types/toast";
import {
  generateCodeChallenge,
  generateCodeVerifier,
  validateVerifier,
  type PkceMethod,
} from "../../../utils/pkce";
import { routePaths } from "../../../utils/routes";

const examples: ToolExample[] = [
  {
    title: "Verifier Example",
    inputLabel: "Code Verifier",
    input: "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk",
    outputLabel: "Use",
    output: "Generated by the OAuth client",
  },
  {
    title: "Challenge Example",
    inputLabel: "Challenge Method",
    input: "S256",
    outputLabel: "Code Challenge",
    output: "E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM",
  },
  {
    title: "Authorization Request Example",
    inputLabel: "Parameters",
    input: "code_challenge=...&code_challenge_method=S256",
    outputLabel: "Sent To",
    output: "Authorization endpoint",
  },
  {
    title: "Token Request Example",
    inputLabel: "Parameter",
    input: "code_verifier=...",
    outputLabel: "Sent To",
    output: "Token endpoint",
  },
];

export function PkceGeneratorToolPage() {
  usePageTitle("PKCE Generator");

  const [verifier, setVerifier] = useState(() => generateCodeVerifier());
  const [challenge, setChallenge] = useState("");
  const [method, setMethod] = useState<PkceMethod>("S256");
  const [error, setError] = useState("");
  const [toast, setToast] = useState<ToastMessage | null>(null);

  useEffect(() => {
    if (!toast) return;
    const timeoutId = window.setTimeout(() => setToast(null), 3200);
    return () => window.clearTimeout(timeoutId);
  }, [toast]);

  function showToast(tone: ToastTone, text: string) {
    setToast({ id: Date.now(), tone, text });
  }

  function handleGenerateVerifier() {
    const nextVerifier = generateCodeVerifier();
    setVerifier(nextVerifier);
    setChallenge("");
    setError("");
    showToast("success", "Code verifier generated.");
  }

  async function handleGenerateChallenge() {
    const validationError = validateVerifier(verifier);
    if (validationError) {
      setError(validationError);
      showToast("failure", "Challenge generation failed.");
      return;
    }

    setChallenge(await generateCodeChallenge(verifier, method));
    setError("");
    showToast("success", "Code challenge generated.");
  }

  async function copyText(value: string, message: string) {
    if (!value) {
      showToast("info", "There is nothing to copy yet.");
      return;
    }

    try {
      await navigator.clipboard.writeText(value);
      showToast("success", message);
    } catch {
      showToast("failure", "Copy failed. Please copy manually.");
    }
  }

  function clearAll() {
    setVerifier("");
    setChallenge("");
    setError("");
    showToast("info", "PKCE values cleared.");
  }

  return (
    <ToolPageLayout
      title="PKCE Generator"
      description="Generate OAuth2 PKCE code verifiers and code challenges."
      breadcrumbs={[
        { label: "Developer Tools", path: routePaths.developerTools },
        { label: "PKCE Generator" },
      ]}
      overviewTitle="What is PKCE?"
      overviewCollapsible
      overviewToggleLabel="What is PKCE?"
      overview={
        <div className="space-y-3">
          <p>PKCE stands for Proof Key for Code Exchange.</p>
          <p>It is used by OAuth2 and OpenID Connect.</p>
          <p>It is commonly required for SPA and mobile applications.</p>
          <p>PKCE helps protect Authorization Code Flow.</p>
        </div>
      }
      inputs={
        <div className="space-y-5">
          <div>
            <div className="mb-2 flex items-center gap-2">
              <label htmlFor="pkce-verifier" className="text-sm font-semibold text-gray-900 dark:text-white">
                Code Verifier
              </label>
              <HelpTooltip title="Verifier" description="Random value generated by the client." exampleInput="dBjftJeZ..." exampleOutput="Used in token request" />
            </div>
            <Textarea id="pkce-verifier" rows={4} value={verifier} onChange={(event) => setVerifier(event.target.value)} className="font-mono" />
          </div>
          <div className="max-w-xs">
            <div className="mb-2 flex items-center gap-2">
              <label htmlFor="pkce-method" className="text-sm font-semibold text-gray-900 dark:text-white">
                Challenge Method
              </label>
              <HelpTooltip title="Method" description="PKCE challenge generation method." exampleInput="S256" exampleOutput="Recommended" />
            </div>
            <Select id="pkce-method" value={method} onChange={(event) => setMethod(event.target.value as PkceMethod)}>
              <option value="S256">S256</option>
              <option value="plain">Plain</option>
            </Select>
          </div>
          {error ? <p className="text-sm font-semibold text-red-600 dark:text-red-300">{error}</p> : null}
          <div className="flex flex-col gap-3 sm:flex-row sm:flex-wrap">
            <Button color="blue" onClick={handleGenerateVerifier}>Generate Verifier</Button>
            <Button color="green" onClick={() => void handleGenerateChallenge()}>Generate Challenge</Button>
            <Button color="light" onClick={() => void copyText(verifier, "Verifier copied.")}>Copy Verifier</Button>
            <Button color="light" onClick={() => void copyText(challenge, "Challenge copied.")}>Copy Challenge</Button>
            <Button color="gray" onClick={clearAll}>Clear</Button>
          </div>
        </div>
      }
      outputs={
        <div className="space-y-5">
          <OutputBlock title="Code Verifier" value={verifier} />
          <div>
            <div className="mb-2 flex items-center gap-2">
              <span className="text-sm font-semibold text-gray-900 dark:text-white">Code Challenge</span>
              <HelpTooltip title="Challenge" description="Derived value sent to the authorization server." exampleInput="Verifier" exampleOutput="S256 challenge" />
            </div>
            <OutputBlock title="Challenge Method" value={method} />
            <OutputBlock title="Code Challenge" value={challenge} />
          </div>
          <section className="rounded-lg border border-cyan-200 bg-cyan-50 p-4 dark:border-cyan-900 dark:bg-cyan-950/40">
            <h2 className="text-sm font-semibold text-gray-950 dark:text-white">OAuth2 Example</h2>
            <pre className="mt-3 overflow-x-auto whitespace-pre-wrap text-sm text-gray-800 dark:text-gray-200">{`Authorization Request
code_challenge=${challenge || "<code_challenge>"}
code_challenge_method=${method}

Token Request
code_verifier=${verifier || "<code_verifier>"}`}</pre>
          </section>
        </div>
      }
      examples={examples}
      notesCollapsible
      notes={
        <ul className="list-disc space-y-2 pl-5 text-sm leading-7 text-gray-600 dark:text-gray-300">
          <li>S256 is the recommended method.</li>
          <li>Plain is supported for compatibility only.</li>
          <li>PKCE is commonly used with Authorization Code Flow.</li>
          <li>Keycloak, Azure AD, Okta and Auth0 support PKCE.</li>
        </ul>
      }
      toast={<ToolToast toast={toast} />}
    />
  );
}

function OutputBlock({ title, value }: { title: string; value: string }) {
  return (
    <div>
      <p className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">{title}</p>
      <pre className="overflow-x-auto rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm text-gray-900 dark:border-gray-700 dark:bg-gray-950 dark:text-gray-100">{value || "-"}</pre>
    </div>
  );
}
