export const routePaths = {
  home: "/",
  about: "/about",
  developerTools: "/developer-tools",
  base64Tool: "/developer-tools/base64",
  uuidTool: "/developer-tools/uuid",
  formatterTool: "/developer-tools/formatter",
  dataCompareTool: "/developer-tools/data-compare",
  timestampTool: "/developer-tools/timestamp",
  jwtDecoderTool: "/developer-tools/jwt-decoder",
  hashGeneratorTool: "/developer-tools/hash-generator",
  regexTesterTool: "/developer-tools/regex-tester",
  urlEncoderDecoderTool: "/developer-tools/url-encoder-decoder",
  pkceGeneratorTool: "/developer-tools/pkce-generator",
  architectureDesign: "/architecture-design",
  adrGenerator: "/architecture-design/adr-generator",
  platformEngineering: "/platform-engineering",
  openShiftCalculator: "/platform-engineering/openshift-calculator",
  jvmMemoryCalculator: "/platform-engineering/jvm-memory-calculator",
  plantUmlViewer: "/architecture-design/plantuml-viewer",
  architectureNotes: "/architecture-notes",
  dpopArchitectureNote: "/architecture-notes/dpop",
} as const;
