export const routePaths = {
  home: "/",
  about: "/about",
  developerTools: "/developer-tools",
  base64Tool: "/developer-tools/base64",
  uuidTool: "/developer-tools/uuid",
  formatterTool: "/developer-tools/formatter",
  dataCompareTool: "/developer-tools/data-compare",
  timestampTool: "/developer-tools/timestamp",
  jwtDecoderTool: "/developer-tools/jwt-decoder",
  hashGeneratorTool: "/developer-tools/hash-generator",
  regexTesterTool: "/developer-tools/regex-tester",
  urlEncoderDecoderTool: "/developer-tools/url-encoder-decoder",
  pkceGeneratorTool: "/developer-tools/pkce-generator",
  platformEngineering: "/platform-engineering/openshift-calculator",
  architectureNotes: "/architecture-notes",
} as const;
